### ISSUE TITLE
Problem with BadPaddingException

### ISSUE THREAD

**Issue by Jacob-S-Scott** [mysto/java-fpe#12]
When running sample code provided there is a compilation error.  See below: 

Exception in thread "main" java.lang.RuntimeException: Uncompilable code - unreported exception javax.crypto.BadPaddingException; must be caught or declared to be thrown

**Comment by bschoening** [comment]
Jacob, what platform and what version of Java?

**Comment by bschoening** [comment]
I'm closing this as there are no details on how to reproduce it and my efforts to run it worked fine.

**Comment by bschoening** [comment]
I'm closing this as there are no details on how to reproduce it and my efforts to run it worked fine.
