### ISSUE TITLE
Maven artifact?

### ISSUE THREAD

**Issue by piotrblasiak** [mysto/java-fpe#2]
Thanks for publishing your work. Do you have any plans on offering this as a maven artifact?

**Comment by bschoening** [comment]
@piotrblasiak Hi, yes, I'm working on it.  I've not published to maven before so its taking a bit of time to figure out the build.gradle.kts, etc.

**Comment by piotrblasiak** [comment]
Ok, great. No stress and appreciate it! Also not sure if you agree but there is quite a bit of logging in the class that I felt like I had to comment out so if you want to make this a consumable package then at least making them .trace instead of .info would make sense in my opinion.
Thanks again!

**Comment by bschoening** [comment]
Piotr, that's a great point and something left over from development.  I've updated the logging to use .trace.

**Comment by bschoening** [comment]
@piotrblasiak I've published it tonight on maven.org.  You can find it at 
https://repo1.maven.org/maven2/io/github/mysto/ff3/.  If you could test it and let me know, that'd be most helpful.

**Comment by piotrblasiak** [comment]
Great - I can't find it in the central maven repo tho? Maybe it takes a while to propagate.

**Comment by bschoening** [comment]
@piotrblasiak should be there now on https://search.maven.org/artifact/io.github.mysto/ff3/0.9/jar

**Comment by piotrblasiak** [comment]
Works great, thanks!
