### ISSUE TITLE
FF3-1 Tweak Length

### ISSUE THREAD

**Issue by presleyduggan** [mysto/java-fpe#3]
I may be doing something incorrectly, but I think you may have a bug checking on the tweak length. I am having difficulties testing the ACVP vectors (56 bit tweak length) and am getting the error: 

`Exception in thread "main" java.lang.IllegalArgumentException: tweak length 7 is invalid: tweak must be 56 or 64 bits
        at FF3Cipher.decrypt(FF3Cipher.java:258)
        at Main.main(Main.java:33)`

It looks like the issue might be here:

Line 140 on FF3Cipher.java
`if ((this.tweakBytes.length != TWEAK_LEN) && (this.tweakBytes.length == TWEAK_LEN_NEW)) {
            throw new IllegalArgumentException(String.format("tweak length %d is invalid: tweak must be 56 or 64 bits",
                    this.tweakBytes.length));
        }`

I believe it should be:

`if ((this.tweakBytes.length != TWEAK_LEN) && (this.tweakBytes.length != TWEAK_LEN_NEW))`

I made this change here and on line 242 and the ACVP vectors are now working and are correct.

ACVP Values I used -

>           "tweak": "CBD09280979564",
> 
>           "tweakLen": 56,
> 
>           "pt": "3992520240",
> 
>           "key": "2DE79D232DF5585D68CE47882AE256D6"

I received the error using
```
String key = "2DE79D232DF5585D68CE47882AE256D6";
String tweak = "CBD09280979564";
FF3Cipher c = new FF3Cipher(key, tweak, "0123456789");
ciphertext = c.encrypt(pt);
```

**Comment by bschoening** [comment]
Yes, that indeed looks like a typo which is causing a bug.  Need to check why the unit tests didn't catch this.  

Thanks for catching this! I've checked in a fix, let me know if that resolve the issue.

**Comment by presleyduggan** [comment]
Works for me now. 

Thanks for putting together this implementation!
