### ISSUE TITLE
Unsupported radix exception for the longest alphabet case

### ISSUE THREAD

**Issue by msochan** [mysto/java-fpe#8]
Passing radix 62 throws an error:

<img width="1803" alt="Screenshot 2022-11-22 at 12 19 22" src="https://user-images.githubusercontent.com/25926105/203301453-c57101f6-2709-4cac-82db-31be97a0ed2f.png">

Created PR to fix this https://github.com/mysto/java-fpe/pull/7

**Comment by bschoening** [comment]
Yes, good catch.  Thanks!

**Comment by bschoening** [comment]
This is worth a patch release, I'll look at making that.

**Comment by msochan** [comment]
Yea, absolutely. Let's go!🔥

**Comment by msochan** [comment]
> This is worth a patch release, I'll look at making that.

Yea, absolutely. Let's go!🔥

**Comment by bschoening** [comment]
I've pushed a new release to trunk and Nexus as 1.0.3.  Let me know if it looks good to you.

**Comment by msochan** [comment]
Everything is looking pretty good!
